baseurl: /
permalink: /:year/:month/:day/:title
title: Mockra
url: http://mockra.com
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
author:
  name: David Ratajczak
  email: david@mockra.com
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
logo:
  /images/dragon.png
description:
  The blog of David Ratajczak, a developer focused on the web.
author:
  David Ratajczak, david@mockra.com
